name: zied_debts
description: "تطبيق زيد اياد للديون - إدارة الديون والمستحقات محلياً بالدينار والدولار"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # Local Database & Storage
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.3

  # Backup, Share & File Management
  share_plus: any
  file_picker: 8.1.4

  # UI, Fonts & 3D Animations
  google_fonts: any
  flutter_animate: any
  fl_chart: any
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
